#ifndef __STRUCTURES_H_
#define __STRUCTURES_H_

// The structure used for a part of the topology (aka for one coordinator)
typedef struct {
    int coordinatorTask; // The coordinator task of a group of workers
    int numberOfWorkerTasks; // The number of workers in that group
    int *workerTasks; // The vector of workers in the group
} Topology;

// The structure used by one task when working with the multipling with 5 task
typedef struct {
    int numberOfElements; // The number of total elements in the numbers vector
    int *numbersVector; // The updated vector (after multipling by 5)
    int *initialVector; // The initial vector (the vector generated by task 0)
} OperationStruct;

#endif /* __STRUCTURES_H_ */